# Generated by Django 4.1.5 on 2023-01-21 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0007_bill_rest_to_pay_dollar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_bs', models.FloatField(default=0)),
                ('amount_dollar', models.FloatField(default=0)),
                ('exchange_rate', models.FloatField(default=0)),
                ('account', models.CharField(default='', max_length=50)),
                ('paid_total', models.BooleanField(default='False')),
                ('description', models.CharField(default='', max_length=200)),
                ('transfer_id', models.CharField(default='', max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
            ],
        ),
    ]
