# Generated by Django 4.1.5 on 2023-01-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_dollar',
            field=models.FloatField(default=0),
        ),
    ]
