# Generated by Django 4.1.5 on 2023-02-23 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_description_alter_account_name'),
        ('payments', '0002_payment_total_dollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_total',
            field=models.BooleanField(default=False),
        ),
    ]
