# Generated by Django 4.1.5 on 2023-01-05 06:23

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=70)),
                ('nickname', models.CharField(max_length=70)),
                ('balance', models.FloatField(default=0)),
                ('taxpayer', models.CharField(choices=[('0', '0% tax retained'), ('75', '75% tax retained'), ('100', '100% tax retained')], max_length=3)),
            ],
        ),
    ]
