# Generated by Django 4.1.5 on 2023-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='balance',
            new_name='bs_debt',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='taxpayer',
            new_name='taxtype',
        ),
        migrations.AddField(
            model_name='provider',
            name='dollar_debt',
            field=models.FloatField(default=0),
        ),
    ]
