# Generated by Django 4.1.5 on 2023-01-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_balance_provider_bs_debt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='bs_debt',
        ),
    ]
