# Generated by Django 4.1.5 on 2023-01-12 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0003_remove_provider_bs_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('bill_number', models.IntegerField()),
                ('emission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount_bs', models.FloatField(default=0)),
                ('sub_total_bs', models.FloatField(default=0)),
                ('tax_bs', models.FloatField(default=0)),
                ('retained_tax_bs', models.FloatField(default=0)),
                ('amount_to_pay_bs', models.FloatField(default=0)),
                ('exchange_fee', models.FloatField(default=0)),
                ('total_amount_dollar', models.FloatField(default=0)),
                ('amount_to_pay_dollar', models.FloatField(default=0)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
        ),
    ]
