# Generated by Django 4.1.5 on 2023-01-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=20),
        ),
    ]
