# Generated by Django 4.1.5 on 2023-01-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_rename_notes_bill_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='exchange_fee',
            new_name='exchange_rate',
        ),
    ]
