# Generated by Django 4.1.5 on 2023-01-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_rename_exchange_fee_bill_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payed',
            field=models.BooleanField(default='False'),
        ),
    ]
