# Generated by Django 4.1.5 on 2023-01-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_bill_payed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='payed',
            new_name='paid',
        ),
    ]
