# Generated by Django 4.1.5 on 2023-01-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_bill_rest_to_pay_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='overdue',
            field=models.FloatField(default=False),
        ),
    ]
