# Generated by Django 4.1.5 on 2023-02-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_overdue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='total_amount_bs',
            new_name='amount_bs',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='total_amount_dollar',
            new_name='amount_dollar',
        ),
        migrations.AddField(
            model_name='bill',
            name='amount_paid_dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_total_dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='retained_tax_dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='sub_total_dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_to_pay_dollar',
            field=models.FloatField(default=0),
        ),
    ]
