# Generated by Django 4.1.5 on 2023-02-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_rename_total_amount_bs_bill_amount_bs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='rest_to_pay_dollar',
        ),
    ]
