# Generated by Django 4.1.5 on 2023-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_remove_bill_rest_to_pay_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='rest_to_pay_dollar',
            field=models.FloatField(default=0),
        ),
    ]
